# Generated by Django 4.1.5 on 2023-01-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='memebership',
            new_name='membership',
        ),
    ]
